name: Python tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pyzmq
            pip install coverage
            pip install -e .
        - name: Run tests and make coverage report
          run: |
            make coverage
        - name: Upload coverage report
          uses: codecov/codecov-action@v1
          with:
            files: ./coverage.xml
            flags: unittests
            env_vars: OS,PYTHON
            fail_ci_if_error: true
            verbose: true
